server:
  port: 5503
  host: localhost
auth:
  jwksUri: http://localhost:5501/.well-known/jwks.json
database:
  url: mongodb://localhost:27017/orderDB?authSource=admin&w=1
client:
  url: http://localhost:3000
